[theme]
# é’ã‚’åŸºèª¿ã¨ã—ãŸã‚¯ãƒªãƒ¼ãƒ³ãªé…è‰²
primaryColor="#4a90e2"
# èƒŒæ™¯ã‚’å°‘ã—ã‚°ãƒ¬ãƒ¼ã«
backgroundColor="#f0f2f6"
# ã‚³ãƒ³ãƒ†ãƒŠãªã©ã®èƒŒæ™¯ã¯ç™½
secondaryBackgroundColor="#ffffff"
textColor="#31333F"
font="sans serif"

[server]
# ã‚³ãƒ¼ãƒ‰ã‚’ä¿å­˜ã—ãŸã¨ãã«è‡ªå‹•ã§å†å®Ÿè¡Œ
runOnSave = true
# ã‚¢ãƒ—ãƒªåã‚’æŒ‡å®š (ã‚µã‚¤ãƒ‰ãƒãƒ¼ã®æœ€ä¸Šéƒ¨ã«è¡¨ç¤ºã•ã‚Œã‚‹åå‰)streamlit.errors.StreamlitAPIException: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:

File "/mount/src/aspecial_education_app/tokusi_app.py", line 15, in <module>
    pg1 = st.Page("main_page.py", title="TOPãƒšãƒ¼ã‚¸", icon="ğŸŒŸ") # TOPãƒšãƒ¼ã‚¸ã‚’ã“ã“ã§ç™»éŒ²ã—ã€è¡¨ç¤ºåã‚’ã€ŒTOPãƒšãƒ¼ã‚¸ã€ã«è¨­å®š
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.12/site-packages/streamlit/navigation/page.py", line 123, in Page
    return StreamlitPage(
           ^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.12/site-packages/streamlit/navigation/page.py", line 186, in __init__
    raise StreamlitAPIException(